# Generated by Django 4.1.1 on 2022-09-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('order_number', models.PositiveSmallIntegerField()),
                ('price_in_dollars', models.PositiveIntegerField()),
                ('price_in_rubs', models.PositiveIntegerField(blank=True, null=True)),
                ('supply_date', models.DateField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
    ]
